### PR TITLE
Laravel 11 Support

### PR DESCRIPTION
**Pull request by swilla**
This is going to require some updates once this PR is merged and a new tag is available: https://github.com/nunomaduro/laravel-console-task/pull/23

### CODE REVIEW

**Comment by fabalv** [comment]
Just a friendly heads-up that the PR you mentioned in the description is unlikely to be merged. Tests aren't passing because the newest version of Phpunit removed a method.

However, a different PR that adds support for Laravel 11 and fixes the tests has been merged already. 

See this tag: https://github.com/nunomaduro/laravel-console-task/releases/tag/v1.9.0

Thanks!

**Comment by manavo** [comment]
Hey @michaeldyrynda, is this likely to be merged anytime soon? Or generally get supported added for Laravel 11?

Thanks!

**Comment by manavo** [comment]
Or @JacobBennett

**Comment by manavo** [comment]
Or I guess #40 might be the better one to merge, which has the updated reference for `nunomaduro/laravel-console-task`?

**Comment by michaeldyrynda** [comment]
Support added via #40 in [3.6.0]https://github.com/thenpingme/thenpingme-laravel/releases/tag/3.6.0)

Sorry for the delay on this - I did look to do it but hit the same console task roadblock. I get so many github notifications via work stuff, that sometimes the other things get lost in the noise 😅

**Comment by manavo** [comment]
Thanks @michaeldyrynda!

**Pull request closed without merging**
